<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Condition="'$(Configuration)' == ''">
		<Configuration>R2026</Configuration>
	</PropertyGroup>
	<PropertyGroup>
		<AssemblyName>CreateWallElevation</AssemblyName>
		<RootNamespace>CreateWallElevationSpectrum</RootNamespace>
		<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
		<Nullable>disable</Nullable>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)' == 'net48'">
		<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
	</PropertyGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net48'">
		<PackageReference Include="System.Resources.Extensions" Version="8.0.0" IncludeAssets="build;compile" PrivateAssets="all" />
	</ItemGroup>
	<ItemGroup>
		<Resource Include="Resources\citrus.ico" />
		<Compile Include="..\Shared\*.cs" Link="Shared\%(Filename)%(Extension)" />
		<Compile Remove="BoundarySimplifier.cs;CreateWallElevationSettings.cs;CreateWallElevationWPF.xaml.cs" />
		<Compile Include="..\CreateWallElevation\BoundarySimplifier.cs" Link="BoundarySimplifier.cs" />
		<Compile Include="..\CreateWallElevation\CreateWallElevationSettings.cs" Link="CreateWallElevationSettings.cs" />
		<Compile Include="..\CreateWallElevation\CreateWallElevationWPF.xaml.cs" Link="CreateWallElevationWPF.xaml.cs" />
	</ItemGroup>
</Project>
